/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jogoLogica_1;

import java.awt.Color;
import java.util.Date;
import javax.swing.JOptionPane;
import jogo.Jogo;
import repositorios.RepositorioTXT;

/**
 * Classe Jogo1 é um form que contém todos os valores e lógica relativos a um dado problema de lógica
 * Agrega uma classe Arquivos a qual pode salvar e recuperar o estatus de um jogo iniciado
 * @author José Weslles
 */
public class Jogo1 extends Jogo {
    
    public String[] lista = new String[20];//Array de Strings para receber valores selecionados para arquivameto e recuperação
    public String dir = "Jogo1";
    RepositorioTXT rep = new RepositorioTXT(lista, dir);
    public Date t = new Date();
    int temp;
    /**
     * Creates new form Jogo1
     */
    public Jogo1() {
        super(new Date());
        
        initComponents();//Metódo que incializa os componentes contidos em Jogo1
    }//Fim do construtor de Jogo1//Fim do construtor de Jogo1

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     
     */
    
    /*Lista Para comparação de respostas.*/
    public void Lista(){
        if(
            box1.getSelectedItem().equals("Vasques") && box2.getSelectedItem().equals("Peixe") && box3.getSelectedItem().equals("Batata") && box4.getSelectedItem().equals("Mate") &&
            box5.getSelectedItem().equals("Vidal") && box6.getSelectedItem().equals("Bife") && box7.getSelectedItem().equals("Purê de abóbora") && box8.getSelectedItem().equals("Limonada") &&
            box9.getSelectedItem().equals("Vieira") && box10.getSelectedItem().equals("Perú") && box11.getSelectedItem().equals("Brócolis") && box12.getSelectedItem().equals("Refrigerante") &&
            box13.getSelectedItem().equals("Vasconcelos") && box14.getSelectedItem().equals("Presunto") && box15.getSelectedItem().equals("Cenoura") && box16.getSelectedItem().equals("Chá gelado") &&
            box17.getSelectedItem().equals("Valença") && box18.getSelectedItem().equals("Frango") && box19.getSelectedItem().equals("Couve") && box20.getSelectedItem().equals("Laranjada")
          ){
            JOptionPane.showMessageDialog(null, "Parabéns, Você concluiu o desafio!");
            super.tempo();
            super.desempenhoJogo();
           }//Fim do bloco condicional que verifica se todos os valores selecionados são verdadeiros
        else
            {
             if(!(box1.getSelectedItem().equals(" ")) && !(box2.getSelectedItem().equals(" ")) && !(box3.getSelectedItem().equals(" ")) && !(box4.getSelectedItem().equals(" ")) &&
                !(box5.getSelectedItem().equals(" ")) && !(box6.getSelectedItem().equals(" ")) && !(box7.getSelectedItem().equals(" ")) && !(box8.getSelectedItem().equals(" ")) &&
                !(box9.getSelectedItem().equals(" ")) && !(box10.getSelectedItem().equals(" ")) && !(box11.getSelectedItem().equals(" ")) && !(box12.getSelectedItem().equals(" ")) &&
                !(box13.getSelectedItem().equals(" ")) && !(box14.getSelectedItem().equals(" ")) && !(box15.getSelectedItem().equals(" ")) && !(box16.getSelectedItem().equals(" ")) &&
                !(box17.getSelectedItem().equals(" ")) && !(box18.getSelectedItem().equals(" ")) && !(box19.getSelectedItem().equals(" ")) && !(box20.getSelectedItem().equals(" ")))
                {
                JOptionPane.showMessageDialog(null, "Respostas incorretas!");
                }//Fim do bloco condicional que verifica se as respostas estão incorretas
            }
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jPopupMenu3 = new javax.swing.JPopupMenu();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel2 = new javax.swing.JPanel();
        box1 = new javax.swing.JComboBox();
        box2 = new javax.swing.JComboBox();
        box3 = new javax.swing.JComboBox();
        box4 = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        box5 = new javax.swing.JComboBox();
        box6 = new javax.swing.JComboBox();
        box7 = new javax.swing.JComboBox();
        box8 = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        box9 = new javax.swing.JComboBox();
        box10 = new javax.swing.JComboBox();
        box11 = new javax.swing.JComboBox();
        box12 = new javax.swing.JComboBox();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        box13 = new javax.swing.JComboBox();
        box14 = new javax.swing.JComboBox();
        box15 = new javax.swing.JComboBox();
        box16 = new javax.swing.JComboBox();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        box17 = new javax.swing.JComboBox();
        box18 = new javax.swing.JComboBox();
        box19 = new javax.swing.JComboBox();
        box20 = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuOpcoes = new javax.swing.JMenu();
        jMenuItemDiagrama = new javax.swing.JMenuItem();
        jMenuItemSalvar = new javax.swing.JMenuItem();
        jMenuItemArquivos = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar2.add(jMenu2);

        jMenu3.setText("jMenu3");

        jMenu4.setText("jMenu4");

        jMenu5.setText("File");
        jMenuBar3.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar3.add(jMenu6);

        jMenu7.setText("File");
        jMenuBar4.add(jMenu7);

        jMenu8.setText("Edit");
        jMenuBar4.add(jMenu8);

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1365, 765));
        setSize(new java.awt.Dimension(1365, 765));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        box1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Valença", "Vasconcelos", "Vidal", "Vieira", "Vasques" }));
        box1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box1ActionPerformed(evt);
            }
        });

        box2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Frango", "Presunto", "Perú", "Bife", "Peixe" }));
        box2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box2ActionPerformed(evt);
            }
        });

        box3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Batata", "Purê de abóbora", "Brócolis", "Cenoura", "Couve" }));
        box3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box3ActionPerformed(evt);
            }
        });

        box4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Laranjada", "Limonada", "Refrigerante", "Chá gelado", "Mate" }));
        box4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box4ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Bruno");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jLabel8))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(box3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(box1, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(box4, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(box2, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(box1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(box2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(box3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(box4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Carolina");

        box5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Valença", "Vasconcelos", "Vidal", "Vieira", "Vasques" }));
        box5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box5ActionPerformed(evt);
            }
        });

        box6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Frango", "Presunto", "Perú", "Bife", "Peixe" }));
        box6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box6ActionPerformed(evt);
            }
        });

        box7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Batata", "Purê de abóbora", "Brócolis", "Cenoura", "Couve" }));
        box7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box7ActionPerformed(evt);
            }
        });

        box8.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Laranjada", "Limonada", "Refrigerante", "Chá gelado", "Mate" }));
        box8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(box5, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel5))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(box6, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(box7, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(box8, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(box5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(box6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(box7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(box8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Davi");

        box9.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Valença", "Vasconcelos", "Vidal", "Vieira", "Vasques" }));
        box9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box9ActionPerformed(evt);
            }
        });

        box10.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Frango", "Presunto", "Perú", "Bife", "Peixe" }));
        box10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box10ActionPerformed(evt);
            }
        });

        box11.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Batata", "Purê de abóbora", "Brócolis", "Cenoura", "Couve" }));
        box11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box11ActionPerformed(evt);
            }
        });

        box12.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Laranjada", "Limonada", "Refrigerante", "Chá gelado", "Mate" }));
        box12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(box9, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(box12, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(box10, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(box11, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(box9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(box10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(box11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(box12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Edna");

        box13.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Valença", "Vasconcelos", "Vidal", "Vieira", "Vasques" }));
        box13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box13ActionPerformed(evt);
            }
        });

        box14.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Frango", "Presunto", "Perú", "Bife", "Peixe" }));
        box14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box14ActionPerformed(evt);
            }
        });

        box15.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Batata", "Purê de abóbora", "Brócolis", "Cenoura", "Couve" }));
        box15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box15ActionPerformed(evt);
            }
        });

        box16.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Laranjada", "Limonada", "Refrigerante", "Chá gelado", "Mate" }));
        box16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box16ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(box13, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(box16, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(box14, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(box15, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(box13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(box14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(box15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(box16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Francisco");

        box17.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Valença", "Vasconcelos", "Vidal", "Vieira", "Vasques" }));
        box17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box17ActionPerformed(evt);
            }
        });

        box18.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Frango", "Presunto", "Perú", "Bife", "Peixe" }));
        box18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box18ActionPerformed(evt);
            }
        });

        box19.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Batata", "Purê de abóbora", "Brócolis", "Cenoura", "Couve" }));
        box19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box19ActionPerformed(evt);
            }
        });

        box20.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Laranjada", "Limonada", "Refrigerante", "Chá gelado", "Mate" }));
        box20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box20ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(jLabel9))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(box19, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(box18, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(box20, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(box17, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(box17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(box18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(box19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(box20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(java.awt.SystemColor.control);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 1, 16)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Bruno e mais quatro amigos do trabalho foram jantar fora, numa sexta feira. Cada um\ndeles pediu um tipo de carne, acompanhamento e bebida diferente da dos outros.\nCom base nas dicas abaixo, tente descobrir o nome completo de cada um, o tipo de\ncarne pedido, o acompanhamento e a babida escolhidos.");
        jTextArea1.setBorder(null);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Comida2.png"))); // NOI18N
        jLabel10.setText("jLabel10");

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Monospaced", 1, 16)); // NOI18N
        jTextField1.setText(" 1- Carolina Pediu o purê de abóbora.");
        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Monospaced", 1, 16)); // NOI18N
        jTextField2.setText(" 2- Davi Vieira não pediu presunto.");
        jTextField2.setBorder(null);

        jTextField4.setEditable(false);
        jTextField4.setFont(new java.awt.Font("Monospaced", 1, 16)); // NOI18N
        jTextField4.setText(" 4- A mulher cujo sobrenome é Vasconcelos, que não pediu couve nem batata, bebeu chá gelado.");
        jTextField4.setBorder(null);

        jTextField3.setEditable(false);
        jTextField3.setFont(new java.awt.Font("Monospaced", 1, 16)); // NOI18N
        jTextField3.setText(" 3- Uma pessoa que não era Francisco nem Edna, pediu peixe com batatas.");
        jTextField3.setBorder(null);

        jTextField5.setEditable(false);
        jTextField5.setFont(new java.awt.Font("Monospaced", 1, 16)); // NOI18N
        jTextField5.setText(" 5- O homem cujo sobrenome é Valença pediu frango, mas não bebeu mate nem limonada.");
        jTextField5.setBorder(null);

        jTextField6.setEditable(false);
        jTextField6.setFont(new java.awt.Font("Monospaced", 1, 16)); // NOI18N
        jTextField6.setText(" 6- A pessoa que pediu brócolis, que não foi nem Francisco nem Bruno, bebeu refrigerante.");
        jTextField6.setBorder(null);

        jTextField7.setEditable(false);
        jTextField7.setFont(new java.awt.Font("Monospaced", 1, 16)); // NOI18N
        jTextField7.setText(" 7- A mulher cujo sobrenome é Vidal bebeu limonada, mas não comeu peixe nem perú.");
        jTextField7.setBorder(null);
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });

        jTextField9.setEditable(false);
        jTextField9.setFont(new java.awt.Font("Monospaced", 1, 16)); // NOI18N
        jTextField9.setText(" 9- Bruno Vasques pediu batatas, mas não bebeu laranjada.");
        jTextField9.setBorder(null);
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });

        jTextField8.setEditable(false);
        jTextField8.setFont(new java.awt.Font("Monospaced", 1, 16)); // NOI18N
        jTextField8.setText(" 8- Edna pediu cenoura, mas não bebeu limonada.");
        jTextField8.setBorder(null);

        jTextField10.setEditable(false);
        jTextField10.setFont(new java.awt.Font("Monospaced", 1, 16)); // NOI18N
        jTextField10.setText(" 10- Carolina não comeu presunto.");
        jTextField10.setBorder(null);
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        jTextField11.setEditable(false);
        jTextField11.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextField11.setText(" Sobrenome");
        jTextField11.setBorder(null);

        jTextField12.setEditable(false);
        jTextField12.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextField12.setText(" Carne");
        jTextField12.setBorder(null);

        jTextField13.setEditable(false);
        jTextField13.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextField13.setText(" Acompanhamento");
        jTextField13.setBorder(null);

        jTextField14.setEditable(false);
        jTextField14.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextField14.setText(" Bebida");
        jTextField14.setBorder(null);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenuOpcoes.setText("Opções");

        jMenuItemDiagrama.setText("Diagrama");
        jMenuItemDiagrama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDiagramaActionPerformed(evt);
            }
        });
        jMenuOpcoes.add(jMenuItemDiagrama);

        jMenuItemSalvar.setText("Salvar");
        jMenuItemSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSalvarActionPerformed(evt);
            }
        });
        jMenuOpcoes.add(jMenuItemSalvar);

        jMenuItemArquivos.setText("Arquivos");
        jMenuItemArquivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemArquivosActionPerformed(evt);
            }
        });
        jMenuOpcoes.add(jMenuItemArquivos);

        jMenuBar1.add(jMenuOpcoes);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 839, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(83, 83, 83)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(343, 343, 343))
        );

        setBounds(0, 0, 1366, 770);
    }// </editor-fold>//GEN-END:initComponents
       /*Item da barra de menu que cria e torna visível um diagrama opcional que ajuda na resolução do problema*/
    private void jMenuItemDiagramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDiagramaActionPerformed
        // TODO add your handling code here:
        new diagrama.Diagrama().setVisible(true);//Cria e torna visível o objeto Diagrama
    }//GEN-LAST:event_jMenuItemDiagramaActionPerformed
        /*Box que contém valores selecionavéis relativos ao item "sobrenome"*/
    private void box1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box1ActionPerformed
        // TODO add your handling code here:
        Lista();
        if((box1.getSelectedItem().equals("Vasques")) && (box3.getSelectedItem().equals("Batata")) && !(box4.getSelectedItem().equals("Laranjada")))
        {
            jTextField9.setBackground(Color.YELLOW);
        }//Fim do bloco condicional que seleciona com cor amarela uma linha específica das dicas do jogo
        else
        {
            jTextField9.setBackground(Color.getColor("Controle"));
        }//Fim do bloco condicional que devolve a cor original a uma linha selecionada
    }//GEN-LAST:event_box1ActionPerformed
        /*Box que contém valores selecionavéis relativos ao item "acompanhamento"*/
    private void box3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box3ActionPerformed
        // TODO add your handling code here:
        Lista();
        if((box1.getSelectedItem().equals("Vasques")) && (box3.getSelectedItem().equals("Batata")) && !(box4.getSelectedItem().equals("Laranjada")))
        {
            jTextField9.setBackground(Color.YELLOW);
            
        }//Fim do bloco condicional que seleciona com cor amarela uma linha específica das dicas do jogo
        else
        {
            jTextField9.setBackground(Color.getColor("Controle"));
        }//Fim do bloco condicional que devolve a cor original a uma linha selecionada
        if((box3.getSelectedItem().equals("Batata")) && (box2.getSelectedItem().equals("Peixe")))
                {
                    jTextField3.setBackground(Color.YELLOW);
                }
        else
        {
            if(((box7.getSelectedItem().equals("Batata")) && (box6.getSelectedItem().equals("Peixe"))) || ((box11.getSelectedItem().equals("Batata")) && (box10.getSelectedItem().equals("Peixe"))))
            {
                jTextField3.setBackground(Color.YELLOW);
            }
            else
            {
            jTextField3.setBackground(Color.getColor("Controle"));
            }
        }
        if(box3.getSelectedItem().equals("Brócolis") && box4.getSelectedItem().equals("Refrigerante"))
        {
            jTextField6.setBackground(Color.YELLOW);
        }
        else
        {
            if(box11.getSelectedItem().equals("Brócolis") && box12.getSelectedItem().equals("Refrigerante"))
            {
                jTextField6.setBackground(Color.YELLOW);
            }
            else
            {
            jTextField6.setBackground(Color.getColor("Controle"));
            }
        }
        if(box1.getSelectedItem().equals("Valença") && box2.getSelectedItem().equals("Frango") && !(box4.getSelectedItem().equals("Mate") || box4.getSelectedItem().equals("Limonada")))
        {
            jTextField5.setBackground(Color.YELLOW);
        }
        else
        {
            if((box9.getSelectedItem().equals("Valença") && box10.getSelectedItem().equals("Frango") && !(box12.getSelectedItem().equals("Mate") || box12.getSelectedItem().equals("Limonada"))) ||
                    (box17.getSelectedItem().equals("Valença") && box18.getSelectedItem().equals("Frango") && !(box20.getSelectedItem().equals("Mate") || box20.getSelectedItem().equals("Limonada"))))
            {
                jTextField5.setBackground(Color.YELLOW);
            }
            else
            {
            jTextField5.setBackground(Color.getColor("Controle"));
            }
        }
        
    }//GEN-LAST:event_box3ActionPerformed

    private void box2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box2ActionPerformed
        // TODO add your handling code here:
        Lista();
        if((box3.getSelectedItem().equals("Batata")) && (box2.getSelectedItem().equals("Peixe")))
                {
                    jTextField3.setBackground(Color.YELLOW);
                }
        else
        {
            if(((box7.getSelectedItem().equals("Batata")) && (box6.getSelectedItem().equals("Peixe"))) || ((box11.getSelectedItem().equals("Batata")) && (box10.getSelectedItem().equals("Peixe"))))
            {
                jTextField3.setBackground(Color.YELLOW);
            }
            else
            {
            jTextField3.setBackground(Color.getColor("Controle"));
            }
        }
        if(box6.getSelectedItem().equals("Bife") && box2.getSelectedItem().equals("Peixe") && box18.getSelectedItem().equals("Frango"))
        {
            jTextField10.setBackground(Color.yellow);
        }
        else
        {
            jTextField10.setBackground(Color.getColor("Controle"));
        }
        if(box1.getSelectedItem().equals("Valença") && box2.getSelectedItem().equals("Frango") && !(box4.getSelectedItem().equals("Mate") || box4.getSelectedItem().equals("Limonada")))
        {
            jTextField5.setBackground(Color.YELLOW);
        }
        else
        {
            if((box9.getSelectedItem().equals("Valença") && box10.getSelectedItem().equals("Frango") && !(box12.getSelectedItem().equals("Mate") || box12.getSelectedItem().equals("Limonada"))) ||
                    (box17.getSelectedItem().equals("Valença") && box18.getSelectedItem().equals("Frango") && !(box20.getSelectedItem().equals("Mate") || box20.getSelectedItem().equals("Limonada"))))
            {
                jTextField5.setBackground(Color.YELLOW);
            }
            else
            {
            jTextField5.setBackground(Color.getColor("Controle"));
            }
        }
    
    }//GEN-LAST:event_box2ActionPerformed

    private void box4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box4ActionPerformed
        // TODO add your handling code here:
        Lista();
        if((box4.getSelectedItem().equals("Laranjada")))
        {
            jTextField9.setBackground(Color.getColor("Controle"));
        }
        else
        {
            if(!(box4.getSelectedItem().equals("Laranjada")) && (box1.getSelectedItem().equals("Vasques")) && (box3.getSelectedItem().equals("Batata")))
            {
                jTextField9.setBackground(Color.YELLOW);
            }
        }
        if(box3.getSelectedItem().equals("Brócolis") && box4.getSelectedItem().equals("Refrigerante"))
        {
            jTextField6.setBackground(Color.yellow);
        }
        else
        {
            if(box11.getSelectedItem().equals("Brócolis") && box12.getSelectedItem().equals("Refrigerante"))
            {
                jTextField6.setBackground(Color.yellow);
            }
            else
            {
            jTextField6.setBackground(Color.getColor("Controle"));
            }
        }
        if(box1.getSelectedItem().equals("Valença") && box2.getSelectedItem().equals("Frango") && !(box4.getSelectedItem().equals("Mate") || box4.getSelectedItem().equals("Limonada")))
        {
            jTextField5.setBackground(Color.YELLOW);
        }
        else
        {
            if((box9.getSelectedItem().equals("Valença") && box10.getSelectedItem().equals("Frango") && !(box12.getSelectedItem().equals("Mate") || box12.getSelectedItem().equals("Limonada"))) ||
                    (box17.getSelectedItem().equals("Valença") && box18.getSelectedItem().equals("Frango") && !(box20.getSelectedItem().equals("Mate") || box20.getSelectedItem().equals("Limonada"))))
            {
                jTextField5.setBackground(Color.YELLOW);
            }
            else
            {
            jTextField5.setBackground(Color.getColor("Controle"));
            }
        }
        
    }//GEN-LAST:event_box4ActionPerformed

    private void box5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box5ActionPerformed
        // TODO add your handling code here:
       Lista();
        if(box5.getSelectedItem().equals("Vasconcelos") && box8.getSelectedItem().equals("Chá gelado") && !(box7.getSelectedItem().equals("Couve") || box7.getSelectedItem().equals("Batata")))
        {
            jTextField4.setBackground(Color.YELLOW);
        }
        else
        {
            if(box13.getSelectedItem().equals("Vasconcelos") && box16.getSelectedItem().equals("Chá gelado") && !(box15.getSelectedItem().equals("Couve") || box15.getSelectedItem().equals("Batata")))
                {
                    jTextField4.setBackground(Color.YELLOW);
                }
            else
            {
            jTextField4.setBackground(Color.getColor("Controle"));
            }
        }
        if((box5.getSelectedItem().equals("Vidal") && box8.getSelectedItem().equals("Limonada")) && !(box6.getSelectedItem().equals("Peixe") || box6.getSelectedItem().equals("Perú")))
        {
            jTextField7.setBackground(Color.YELLOW);
        }
        else
        {
            if((box13.getSelectedItem().equals("Vidal") && box16.getSelectedItem().equals("Limonada")) && !(box14.getSelectedItem().equals("Peixe") || box14.getSelectedItem().equals("Perú")))
            {
                jTextField7.setBackground(Color.YELLOW);
            }
            else
            {
            jTextField7.setBackground(Color.getColor("Controle"));
            }
        }
        
    }//GEN-LAST:event_box5ActionPerformed

    private void box6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box6ActionPerformed
        // TODO add your handling code here:
        Lista();
        if((box6.getSelectedItem().equals("Presunto")))
        {
            jTextField10.setBackground(Color.getColor("Controle"));
        }
        if(((box7.getSelectedItem().equals("Batata")) && (box6.getSelectedItem().equals("Peixe"))) && !((box3.getSelectedItem().equals("Batata")) && (box2.getSelectedItem().equals("Peixe"))))
                {
                    jTextField3.setBackground(Color.YELLOW);
                }
        else
        {
            if(((box3.getSelectedItem().equals("Batata")) && (box2.getSelectedItem().equals("Peixe"))) || ((box11.getSelectedItem().equals("Batata")) && (box10.getSelectedItem().equals("Peixe"))))
            {
                jTextField3.setBackground(Color.YELLOW);
            }
            else
            {
            jTextField3.setBackground(Color.getColor("Controle"));
            }
        }
        if(box6.getSelectedItem().equals("Bife") && box2.getSelectedItem().equals("Peixe") && box18.getSelectedItem().equals("Frango"))
        {
            jTextField10.setBackground(Color.YELLOW);
        }
        else
        {
            jTextField10.setBackground(Color.getColor("Controle"));
        }
        if((box5.getSelectedItem().equals("Vidal") && box8.getSelectedItem().equals("Limonada")) && !(box6.getSelectedItem().equals("Peixe") || box6.getSelectedItem().equals("Perú")))
        {
            jTextField7.setBackground(Color.YELLOW);
        }
        else
        {
            if((box13.getSelectedItem().equals("Vidal") && box16.getSelectedItem().equals("Limonada")) && !(box14.getSelectedItem().equals("Peixe") || box14.getSelectedItem().equals("Perú")))
            {
                jTextField7.setBackground(Color.YELLOW);
            }
            else
            {
            jTextField7.setBackground(Color.getColor("Controle"));
            }
        }
        
    }//GEN-LAST:event_box6ActionPerformed

    private void box7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box7ActionPerformed
        // TODO add your handling code here:
        Lista();
        if(box7.getSelectedItem().equals("Purê de abóbora") && !(box6.getSelectedItem().equals("Presunto")))
        {
            jTextField1.setBackground(Color.YELLOW);
        }
        else
        {
            jTextField1.setBackground(Color.getColor("Controle"));
        }
        if(((box7.getSelectedItem().equals("Batata")) && (box6.getSelectedItem().equals("Peixe"))) && !((box3.getSelectedItem().equals("Batata")) && (box2.getSelectedItem().equals("Peixe"))))
                {
                    jTextField3.setBackground(Color.YELLOW);
                }
        else
        {
            if(((box3.getSelectedItem().equals("Batata")) && (box2.getSelectedItem().equals("Peixe"))) || ((box11.getSelectedItem().equals("Batata")) && (box10.getSelectedItem().equals("Peixe"))))
            {
                jTextField3.setBackground(Color.YELLOW);
            }
            else
            {
            jTextField3.setBackground(Color.getColor("Controle"));
            }
        }
        
        if(box5.getSelectedItem().equals("Vasconcelos") && box8.getSelectedItem().equals("Chá gelado") && !(box7.getSelectedItem().equals("Couve") || box7.getSelectedItem().equals("Batata")))
        {
            jTextField4.setBackground(Color.YELLOW);
        }
        else
        {
            if(box13.getSelectedItem().equals("Vasconcelos") && box16.getSelectedItem().equals("Chá gelado") && !(box15.getSelectedItem().equals("Couve") || box15.getSelectedItem().equals("Batata")))
                {
                    jTextField4.setBackground(Color.YELLOW);
                }
            else
            {
            jTextField4.setBackground(Color.getColor("Controle"));
            }
        }
        
    }//GEN-LAST:event_box7ActionPerformed

    private void box8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box8ActionPerformed
        // TODO add your handling code here:
        Lista();
        if(box5.getSelectedItem().equals("Vasconcelos") && box8.getSelectedItem().equals("Chá gelado") && !(box7.getSelectedItem().equals("Couve") || box7.getSelectedItem().equals("Batata")))
        {
            jTextField4.setBackground(Color.YELLOW);
        }
        else
        {
            if(box13.getSelectedItem().equals("Vasconcelos") && box16.getSelectedItem().equals("Chá gelado") && !(box15.getSelectedItem().equals("Couve") || box15.getSelectedItem().equals("Batata")))
                {
                    jTextField4.setBackground(Color.YELLOW);
                }
            else
            {
            jTextField4.setBackground(Color.getColor("Controle"));
            }
        }
        if((box5.getSelectedItem().equals("Vidal") && box8.getSelectedItem().equals("Limonada")) && !(box6.getSelectedItem().equals("Peixe") || box6.getSelectedItem().equals("Perú")))
        {
            jTextField7.setBackground(Color.YELLOW);
        }
        else
        {
            if((box13.getSelectedItem().equals("Vidal") && box16.getSelectedItem().equals("Limonada")) && !(box14.getSelectedItem().equals("Peixe") || box14.getSelectedItem().equals("Perú")))
            {
                jTextField7.setBackground(Color.YELLOW);
            }
            else
            {
            jTextField7.setBackground(Color.getColor("Controle"));
            }
        }
        
    }//GEN-LAST:event_box8ActionPerformed

    private void box9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box9ActionPerformed
        // TODO add your handling code here:
        Lista();
        if((box9.getSelectedItem().equals("Vieira")) && (!(box10.getSelectedItem().equals("Presunto"))))
        {
            jTextField2.setBackground(Color.YELLOW);
        }
        else
        {
            jTextField2.setBackground(Color.getColor("Controle"));
        }
        if(box9.getSelectedItem().equals("Valença") && box10.getSelectedItem().equals("Frango") && !(box12.getSelectedItem().equals("Mate") || box12.getSelectedItem().equals("Limonada")))
        {
            jTextField5.setBackground(Color.YELLOW);
        }
        else
        {
            if((box1.getSelectedItem().equals("Valença") && box2.getSelectedItem().equals("Frango") && !(box4.getSelectedItem().equals("Mate") || box4.getSelectedItem().equals("Limonada"))) ||
                    (box17.getSelectedItem().equals("Valença") && box18.getSelectedItem().equals("Frango") && !(box20.getSelectedItem().equals("Mate") || box20.getSelectedItem().equals("Limonada"))))
            {
                jTextField5.setBackground(Color.YELLOW);
            }
            else
            {
            jTextField5.setBackground(Color.getColor("Controle"));
            }
        }
        
    }//GEN-LAST:event_box9ActionPerformed

    private void box10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box10ActionPerformed
        // TODO add your handling code here:
        Lista();
        if((box11.getSelectedItem().equals("Batata")) && (box10.getSelectedItem().equals("Peixe")))
                {
                    jTextField3.setBackground(Color.YELLOW);
                }
        else
        {
            if(((box3.getSelectedItem().equals("Batata")) && (box2.getSelectedItem().equals("Peixe"))) || ((box7.getSelectedItem().equals("Batata")) && (box6.getSelectedItem().equals("Peixe"))))
            {
                jTextField3.setBackground(Color.YELLOW);
            }
            else
            {
            jTextField3.setBackground(Color.getColor("Controle"));
            }
        }
        if(box9.getSelectedItem().equals("Valença") && box10.getSelectedItem().equals("Frango") && !(box12.getSelectedItem().equals("Mate") || box12.getSelectedItem().equals("Limonada")))
        {
            jTextField5.setBackground(Color.YELLOW);
        }
        else
        {
            if((box1.getSelectedItem().equals("Valença") && box2.getSelectedItem().equals("Frango") && !(box4.getSelectedItem().equals("Mate") || box4.getSelectedItem().equals("Limonada"))) ||
                    (box17.getSelectedItem().equals("Valença") && box18.getSelectedItem().equals("Frango") && !(box20.getSelectedItem().equals("Mate") || box20.getSelectedItem().equals("Limonada"))))
            {
                jTextField5.setBackground(Color.YELLOW);
            }
            else
            {
            jTextField5.setBackground(Color.getColor("Controle"));
            }
        }
        
    }//GEN-LAST:event_box10ActionPerformed

    private void box11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box11ActionPerformed
        // TODO add your handling code here:
        Lista();
        if((box11.getSelectedItem().equals("Batata")) && (box10.getSelectedItem().equals("Peixe")))
                {
                    jTextField3.setBackground(Color.YELLOW);
                }
        else
        {
            if(((box3.getSelectedItem().equals("Batata")) && (box2.getSelectedItem().equals("Peixe"))) || ((box7.getSelectedItem().equals("Batata")) && (box6.getSelectedItem().equals("Peixe"))))
            {
                jTextField3.setBackground(Color.YELLOW);
            }
            else
            {
            jTextField3.setBackground(Color.getColor("Controle"));
            }
        }
        if(box11.getSelectedItem().equals("Brócolis") && box12.getSelectedItem().equals("Refrigerante"))
        {
            jTextField6.setBackground(Color.yellow);
        }
        else
        {
            if(box3.getSelectedItem().equals("Brócolis") && box4.getSelectedItem().equals("Refrigerante"))
            {
                jTextField6.setBackground(Color.yellow);
            }
            else
            {
            jTextField6.setBackground(Color.getColor("Controle"));
            }
        }
        
    }//GEN-LAST:event_box11ActionPerformed

    private void box12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box12ActionPerformed
        // TODO add your handling code here:
        Lista();
        if(box11.getSelectedItem().equals("Brócolis") && box12.getSelectedItem().equals("Refrigerante"))
        {
            jTextField6.setBackground(Color.yellow);
        }
        else
        {
            if(box3.getSelectedItem().equals("Brócolis") && box4.getSelectedItem().equals("Refrigerante"))
            {
                jTextField6.setBackground(Color.yellow);
            }
            else
            {
            jTextField6.setBackground(Color.getColor("Controle"));
            }
        }
        if(box9.getSelectedItem().equals("Valença") && box10.getSelectedItem().equals("Frango") && !(box12.getSelectedItem().equals("Mate") || box12.getSelectedItem().equals("Limonada")))
        {
            jTextField5.setBackground(Color.YELLOW);
        }
        else
        {
            if((box1.getSelectedItem().equals("Valença") && box2.getSelectedItem().equals("Frango") && !(box4.getSelectedItem().equals("Mate") || box4.getSelectedItem().equals("Limonada"))) ||
                    (box17.getSelectedItem().equals("Valença") && box18.getSelectedItem().equals("Frango") && !(box20.getSelectedItem().equals("Mate") || box20.getSelectedItem().equals("Limonada"))))
            {
                jTextField5.setBackground(Color.YELLOW);
            }
            else
            {
            jTextField5.setBackground(Color.getColor("Controle"));
            }
        }
        
    }//GEN-LAST:event_box12ActionPerformed

    private void box13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box13ActionPerformed
        // TODO add your handling code here:
        Lista();
        if((box13.getSelectedItem().equals("Vasconcelos") && box16.getSelectedItem().equals("Chá gelado")) && !(box15.getSelectedItem().equals("Batata") || box15.getSelectedItem().equals("Couve")))
        {
            jTextField4.setBackground(Color.YELLOW);
        }
        else
        {
            if(box5.getSelectedItem().equals("Vasconcelos") && box8.getSelectedItem().equals("Chá gelado") && !(box7.getSelectedItem().equals("Couve") || box7.getSelectedItem().equals("Batata")))
                {
                    jTextField4.setBackground(Color.YELLOW);
                }
            else
            {
            jTextField4.setBackground(Color.getColor("Controle"));
            }
        }
        if((box13.getSelectedItem().equals("Vidal") && box16.getSelectedItem().equals("Limonada")) && !(box14.getSelectedItem().equals("Peixe") || box14.getSelectedItem().equals("Perú")))
        {
            jTextField7.setBackground(Color.YELLOW);
        }
        else
        {
            if((box5.getSelectedItem().equals("Vidal") && box8.getSelectedItem().equals("Limonada")) && !(box6.getSelectedItem().equals("Peixe") || box6.getSelectedItem().equals("Perú")))
            {
                jTextField7.setBackground(Color.YELLOW);
            }
            else
            {
            jTextField7.setBackground(Color.getColor("Controle"));
            }
        }
        
    }//GEN-LAST:event_box13ActionPerformed

    private void box14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box14ActionPerformed
        // TODO add your handling code here:
        Lista();
        if((box13.getSelectedItem().equals("Vidal") && box16.getSelectedItem().equals("Limonada")) && !(box14.getSelectedItem().equals("Peixe") || box14.getSelectedItem().equals("Perú")))
        {
            jTextField7.setBackground(Color.YELLOW);
        }
        else
        {
            if((box5.getSelectedItem().equals("Vidal") && box8.getSelectedItem().equals("Limonada")) && !(box6.getSelectedItem().equals("Peixe") || box6.getSelectedItem().equals("Perú")))
            {
                jTextField7.setBackground(Color.YELLOW);
            }
            else
            {
            jTextField7.setBackground(Color.getColor("Controle"));
            }
        }
        
    }//GEN-LAST:event_box14ActionPerformed

    private void box15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box15ActionPerformed
        // TODO add your handling code here:
        Lista();
        if((box15.getSelectedItem().equals("Cenoura")) && !(box16.getSelectedItem().equals("Limonada")))
        {
            jTextField8.setBackground(Color.YELLOW);
        }
        else
        {
            jTextField8.setBackground(Color.getColor("Controle"));
        }
        if((box13.getSelectedItem().equals("Vasconcelos") && box16.getSelectedItem().equals("Chá gelado")) && !(box15.getSelectedItem().equals("Batata") || box15.getSelectedItem().equals("Couve")))
        {
            jTextField4.setBackground(Color.yellow);
        }
        else
        {
            jTextField4.setBackground(Color.getColor("Controle"));
        }
        if((box13.getSelectedItem().equals("Vidal") && box16.getSelectedItem().equals("Limonada")) && !(box14.getSelectedItem().equals("Peixe") || box14.getSelectedItem().equals("Perú")))
        {
            jTextField7.setBackground(Color.YELLOW);
        }
        else
        {
            if((box5.getSelectedItem().equals("Vidal") && box8.getSelectedItem().equals("Limonada")) && !(box6.getSelectedItem().equals("Peixe") || box6.getSelectedItem().equals("Perú")))
            {
                jTextField7.setBackground(Color.YELLOW);
            }
            else
            {
            jTextField7.setBackground(Color.getColor("Controle"));
            }
        }
        
    }//GEN-LAST:event_box15ActionPerformed

    private void box16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box16ActionPerformed
        // TODO add your handling code here:
        Lista();
        if((box16.getSelectedItem().equals("Limonada")))
                {
                    jTextField8.setBackground(Color.getColor("Controle"));
                }
        else
        {
            if(!(box16.getSelectedItem().equals("Limonada")) && (box15.getSelectedItem().equals("Cenoura")))
            {
                jTextField8.setBackground(Color.YELLOW);
            }
        }
        if((box13.getSelectedItem().equals("Vasconcelos") && box16.getSelectedItem().equals("Chá gelado")) && !(box15.getSelectedItem().equals("Batata") || box15.getSelectedItem().equals("Couve")))
        {
            jTextField4.setBackground(Color.YELLOW);
        }
        else
        {
            if((box5.getSelectedItem().equals("Vasconcelos") && box8.getSelectedItem().equals("Chá gelado")) && !(box7.getSelectedItem().equals("Batata") || box7.getSelectedItem().equals("Couve")))
            {
                jTextField4.setBackground(Color.YELLOW);
            }
            else
            {
            jTextField4.setBackground(Color.getColor("Controle"));
            }
        }
        if((box13.getSelectedItem().equals("Vidal") && box16.getSelectedItem().equals("Limonada")) && !(box14.getSelectedItem().equals("Peixe") || box14.getSelectedItem().equals("Perú")))
        {
            jTextField7.setBackground(Color.YELLOW);
        }
        else
        {
            if((box5.getSelectedItem().equals("Vidal") && box8.getSelectedItem().equals("Limonada")) && !(box6.getSelectedItem().equals("Peixe") || box6.getSelectedItem().equals("Perú")))
            {
                jTextField7.setBackground(Color.YELLOW);
            }
            else
            {
            jTextField7.setBackground(Color.getColor("Controle"));
            }
        }
        
    }//GEN-LAST:event_box16ActionPerformed

    private void box17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box17ActionPerformed
        // TODO add your handling code here:
        Lista();
        if(box17.getSelectedItem().equals("Valença") && box18.getSelectedItem().equals("Frango") && !(box20.getSelectedItem().equals("Mate") || box20.getSelectedItem().equals("Limonada")))
        {
            jTextField5.setBackground(Color.YELLOW);
        }
        else
        {
            if((box1.getSelectedItem().equals("Valença") && box2.getSelectedItem().equals("Frango") && !(box4.getSelectedItem().equals("Mate") || box4.getSelectedItem().equals("Limonada"))) ||
                    (box9.getSelectedItem().equals("Valença") && box10.getSelectedItem().equals("Frango") && !(box12.getSelectedItem().equals("Mate") || box12.getSelectedItem().equals("Limonada"))))
            {
                jTextField5.setBackground(Color.YELLOW);
            }
            else
            {
            jTextField5.setBackground(Color.getColor("Controle"));
            }
        }
        
    }//GEN-LAST:event_box17ActionPerformed

    private void box18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box18ActionPerformed
        // TODO add your handling code here:
        Lista();
        if(box17.getSelectedItem().equals("Valença") && box18.getSelectedItem().equals("Frango") && !(box20.getSelectedItem().equals("Mate") || box20.getSelectedItem().equals("Limonada")))
        {
            jTextField5.setBackground(Color.YELLOW);
        }
        else
        {
            if((box1.getSelectedItem().equals("Valença") && box2.getSelectedItem().equals("Frango") && !(box4.getSelectedItem().equals("Mate") || box4.getSelectedItem().equals("Limonada"))) ||
                    (box9.getSelectedItem().equals("Valença") && box10.getSelectedItem().equals("Frango") && !(box12.getSelectedItem().equals("Mate") || box12.getSelectedItem().equals("Limonada"))))
            {
                jTextField5.setBackground(Color.YELLOW);
            }
            else
            {
            jTextField5.setBackground(Color.getColor("Controle"));
            }
        }
        if(box6.getSelectedItem().equals("Bife") && box2.getSelectedItem().equals("Peixe") && box18.getSelectedItem().equals("Frango"))
        {
            jTextField10.setBackground(Color.yellow);
        }
        else
        {
            jTextField10.setBackground(Color.getColor("Controle"));
        }
        
    }//GEN-LAST:event_box18ActionPerformed

    private void box19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box19ActionPerformed
        // TODO add your handling code here:
        Lista();
    }//GEN-LAST:event_box19ActionPerformed

    private void box20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box20ActionPerformed
        // TODO add your handling code here:
        Lista();
        if(box17.getSelectedItem().equals("Valença") && box18.getSelectedItem().equals("Frango") && !(box20.getSelectedItem().equals("Mate") || box20.getSelectedItem().equals("Limonada")))
        {
            jTextField5.setBackground(Color.YELLOW);
        }
        else
        {
            if((box1.getSelectedItem().equals("Valença") && box2.getSelectedItem().equals("Frango") && !(box4.getSelectedItem().equals("Mate") || box4.getSelectedItem().equals("Limonada"))) ||
                    (box9.getSelectedItem().equals("Valença") && box10.getSelectedItem().equals("Frango") && !(box12.getSelectedItem().equals("Mate") || box12.getSelectedItem().equals("Limonada"))))
            {
                jTextField5.setBackground(Color.YELLOW);
            }
            else
            {
            jTextField5.setBackground(Color.getColor("Controle"));
            }
        }
        
    }//GEN-LAST:event_box20ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here: 
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed
        /*Item da barra de menu que carrega os valores selcinados no Array de Strings para arquivamento*/
    private void jMenuItemSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSalvarActionPerformed
        // TODO add your handling code here:
        lista[0] = (String) box1.getSelectedItem();
        lista[1] = (String) box2.getSelectedItem();
        lista[2] = (String) box3.getSelectedItem();
        lista[3] = (String) box4.getSelectedItem();
        lista[4] = (String) box5.getSelectedItem();
        lista[5] = (String) box6.getSelectedItem();
        lista[6] = (String) box7.getSelectedItem();
        lista[7] = (String) box8.getSelectedItem();
        lista[8] = (String) box9.getSelectedItem();
        lista[9] = (String) box10.getSelectedItem();
        lista[10] = (String) box11.getSelectedItem();
        lista[11] = (String) box12.getSelectedItem();
        lista[12] = (String) box13.getSelectedItem();
        lista[13] = (String) box14.getSelectedItem();
        lista[14] = (String) box15.getSelectedItem();
        lista[15] = (String) box16.getSelectedItem();
        lista[16] = (String) box17.getSelectedItem();
        lista[17] = (String) box18.getSelectedItem();
        lista[18] = (String) box19.getSelectedItem();
        lista[19] = (String)box20.getSelectedItem();
        rep.setListas(lista);
        rep.armazenar();
    }//GEN-LAST:event_jMenuItemSalvarActionPerformed
        /*Item da barra de menu que recupara um dado arquivo relativo ao Jogo1*/
    private void jMenuItemArquivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemArquivosActionPerformed
        /*Carrega o Array de Strings com os valores atuais*/
        lista[0] = (String) box1.getSelectedItem();
        lista[1] = (String) box2.getSelectedItem();
        lista[2] = (String) box3.getSelectedItem();
        lista[3] = (String) box4.getSelectedItem();
        lista[4] = (String) box5.getSelectedItem();
        lista[5] = (String) box6.getSelectedItem();
        lista[6] = (String) box7.getSelectedItem();
        lista[7] = (String) box8.getSelectedItem();
        lista[8] = (String) box9.getSelectedItem();
        lista[9] = (String) box10.getSelectedItem();
        lista[10] = (String) box11.getSelectedItem();
        lista[11] = (String) box12.getSelectedItem();
        lista[12] = (String) box13.getSelectedItem();
        lista[13] = (String) box14.getSelectedItem();
        lista[14] = (String) box15.getSelectedItem();
        lista[15] = (String) box16.getSelectedItem();
        lista[16] = (String) box17.getSelectedItem();
        lista[17] = (String) box18.getSelectedItem();
        lista[18] = (String) box19.getSelectedItem();
        lista[19] = (String)box20.getSelectedItem();
        /*Limpa os campos das caixas de seleção para evitar conflito na recuperação de arquivo*/
        box1.setSelectedItem(" ");
        box2.setSelectedItem(" ");
        box3.setSelectedItem(" ");
        box4.setSelectedItem(" ");
        box5.setSelectedItem(" ");
        box6.setSelectedItem(" ");
        box7.setSelectedItem(" ");
        box8.setSelectedItem(" ");
        box9.setSelectedItem(" ");
        box10.setSelectedItem(" ");
        box11.setSelectedItem(" ");
        box12.setSelectedItem(" ");
        box13.setSelectedItem(" ");
        box14.setSelectedItem(" ");
        box15.setSelectedItem(" ");
        box16.setSelectedItem(" ");
        box17.setSelectedItem(" ");
        box18.setSelectedItem(" ");
        box19.setSelectedItem(" ");
        box20.setSelectedItem(" ");
        try{
            lista = rep.recuperaArquivo();//Invoca o método que recupera arquivos
            /*Carrega nas caixas de seleção os valores retornados pelo método que recupera arquivos*/
            box1.setSelectedItem(lista[0]);
            box2.setSelectedItem(lista[1]);
            box3.setSelectedItem(lista[2]);
            box4.setSelectedItem(lista[3]);
            box5.setSelectedItem(lista[4]);
            box6.setSelectedItem(lista[5]);
            box7.setSelectedItem(lista[6]);
            box8.setSelectedItem(lista[7]);
            box9.setSelectedItem(lista[8]);
            box10.setSelectedItem(lista[9]);
            box11.setSelectedItem(lista[10]);
            box12.setSelectedItem(lista[11]);
            box13.setSelectedItem(lista[12]);
            box14.setSelectedItem(lista[13]);
            box15.setSelectedItem(lista[14]);
            box16.setSelectedItem(lista[15]);
            box17.setSelectedItem(lista[16]);
            box18.setSelectedItem(lista[17]);
            box19.setSelectedItem(lista[18]);
            box20.setSelectedItem(lista[19]);
        }catch(NullPointerException e){
            JOptionPane.showMessageDialog(null, "Erro no sistema!");
        }//Menssagem em caixa de diálogo no caso de erro de recuperação de arquivo
    }//GEN-LAST:event_jMenuItemArquivosActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jogo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jogo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jogo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jogo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jogo1().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox box1;
    private javax.swing.JComboBox box10;
    private javax.swing.JComboBox box11;
    private javax.swing.JComboBox box12;
    private javax.swing.JComboBox box13;
    private javax.swing.JComboBox box14;
    private javax.swing.JComboBox box15;
    private javax.swing.JComboBox box16;
    private javax.swing.JComboBox box17;
    private javax.swing.JComboBox box18;
    private javax.swing.JComboBox box19;
    private javax.swing.JComboBox box2;
    private javax.swing.JComboBox box20;
    private javax.swing.JComboBox box3;
    private javax.swing.JComboBox box4;
    private javax.swing.JComboBox box5;
    private javax.swing.JComboBox box6;
    private javax.swing.JComboBox box7;
    private javax.swing.JComboBox box8;
    private javax.swing.JComboBox box9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemArquivos;
    private javax.swing.JMenuItem jMenuItemDiagrama;
    private javax.swing.JMenuItem jMenuItemSalvar;
    private javax.swing.JMenu jMenuOpcoes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPopupMenu jPopupMenu3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
    
}
